version: "3.7"
services:
  minecraft:
    restart: always
  backup:
    restart: always
  prometheus:
    restart: always
    build:
      context: ../monitoring/prometheus
  grafana:
    restart: always
    build:
      context: ../monitoring/grafana
  exporter:
    restart: always
  portainer:
    restart: always
