version: "3.7"
services:
  traefik:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  minecraft:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
