version: '3.7'
services:
  traefik:
    secrets:
      - traefik_users
      - prometheus_users
  grafana:
    secrets:
      - grafana_password

secrets:
  traefik_users:
    file: ../traefik_users
  grafana_password:
    file: ../grafana_password
  prometheus_users:
    file: ../prometheus_users
