version: '3.7'
services:
  minecraft:
    environment:
      VERSION: "1.15.2"
      TYPE: PAPER
      EULA: "true"
      USE_AIKAR_FLAGS: "true"
      ENABLE_RCON: "true"
      RCON_PASSWORD: "password"
      RCON_PORT: 28016
  backup:
    environment:
      RCON_HOST: minecraft
      RCON_PASSWORD: "password"
      RCON_PORT: 28016
      BACKUP_METHOD: "tar"
      LINK_LATEST: "true"
